# SPDX-LICENSE-IDENTIFIER: GPL-2.0-ONLY
# (C) 2024 Author: <kisfg@hotmail.com>
# DEFINE AS A SAMPLE.
local:
  InterceptorPort: 53197
  ProxySocket: "[::1]:9971"
  AsymmetricCipher: "sm2"
  StreamCipher: "chacha20poly1305"
  HashCipher: "sha512"
  CompressedAlgorithm: "null"
  AccessToken: "56e0daatriei6o5i" # should save in a file called `./.accessToken.txt` located in father dir.
  